name: archive

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed    

jobs:
  deploy:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_repository.full_name == 'Villavu/Simba'
    runs-on: ubuntu-latest
    steps:     
      - name: Download artifacts
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var fs = require('fs');
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            for (artifact of artifacts.data.artifacts) {
              var download = await github.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: artifact.id,
                 archive_format: 'zip',
              });
              fs.writeFileSync(artifact.name + '.zip', Buffer.from(download.data));

              console.log('Downloaded: ' + artifact.name);
            }

      - name: Unzip
        shell: bash
        run: |
          mkdir binaries
          unzip '*.zip' -d binaries  

      - name: Push
        shell: bash     
        run: |
          git config --global http.postBuffer 500M
          git config --global user.email "villavu-bot"
          git config --global user.name "villavu-bot"
          git clone https://${{ secrets.API_TOKEN_GITHUB }}@github.com/Villavu/Simba-Build-Archive

          date_year=$(date +"%Y")
          date_month_day=$(date +"%m-%d")

          branch=${{ github.event.workflow_run.head_branch }}
          commit=${{ github.event.workflow_run.head_sha }}

          cd Simba-Build-Archive
          
          mkdir -p "$date_year/$date_month_day $branch $commit"
          mv ../binaries/* "$date_year/$date_month_day $branch $commit"

          sed -i "6 i $date_year/$date_month_day | $branch | [$commit](https://github.com/Villavu/Simba/commit/$commit) | [Link](https://github.com/Villavu/Simba-Build-Archive/tree/main/$date_year/$date_month_day%20$branch%20$commit)" README.md

          git add .
          git commit --message "${{ github.event.workflow_run.head_sha }}"
          git push https://${{ secrets.API_TOKEN_GITHUB }}@github.com/villavu/simba-build-archive