name: archive

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed    

jobs:
  deploy:
    if: github.event.workflow_run.event == 'push' && github.event.workflow_run.head_repository.full_name == 'Villavu/Simba'
    runs-on: ubuntu-latest
    steps:     
      - name: Download artifacts
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var fs = require('fs');
            var artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{ github.event.workflow_run.id }},
            });
            for (artifact of artifacts.data.artifacts) {
              var download = await github.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: artifact.id,
                 archive_format: 'zip',
              });
              fs.writeFileSync(artifact.name + '.zip', Buffer.from(download.data));

              console.log('Downloaded: ' + artifact.name);
            }

      - name: Unzip
        shell: bash
        run: |
          mkdir binaries
          unzip '*.zip' -d binaries  

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"

      - name: Push
        uses: cpina/github-action-push-to-another-repository@v1.5
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'binaries'
          target-directory: ${{ steps.date.outputs.date }} ${{ github.event.workflow_run.head_sha }}
          destination-github-username: 'villavu'
          destination-repository-name: 'simba-build-archive'
          commit-message: ${{ github.event.workflow_run.head_sha }}
          user-email: 'villavu-bot'
          user-name: 'villavu-bot'
          target-branch: main