name: Auto Build

on: [push]

jobs:
  test:
    name: Test
    runs-on: arm64
    steps:
    - uses: actions/checkout@v1

    - name: Test
      run: |
       lazbuild ${{ env.LAZ_OPT }} --build-mode=Release "Projects/Simba/Simba.lpi"