name: Build

on: 
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.runs-on }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        config:            
          - name: Windows 64
            runs-on: windows-latest
            cpu: x86_64
            build-mode: SIMBA_WIN64
            binary: Simba-Win64.exe
            test: Simba-Win64.exe
            
          - name: Windows 32  
            runs-on: windows-latest
            cpu: i386
            build-mode: SIMBA_WIN32
            binary: Simba-Win32.exe
            test: Simba-Win32.exe

          - name: Linux 64
            runs-on: ubuntu-latest
            cpu: x86_64
            build-mode: SIMBA_LINUX64
            binary: Simba-Linux64
            test: Simba-Linux64
          
          - name: AArch64  
            runs-on: ubuntu-latest
            cpu: aarch64
            build-mode: SIMBA_AARCH64
            binary: Simba-AArch64
            
          - name: MacOS 64
            runs-on: macos-latest
            cpu: x86_64
            build-mode: SIMBA_DARWIN64
            binary: Simba-Darwin64.zip
            test: Simba-Darwin64
            
    steps:
      - uses: actions/checkout@v2.3.4
        with: 
          submodules: true
      
      - name: Install Lazarus
        uses: ollydev/setup-lazarus-fpcup@v2.3
        with:
          cpu: ${{ matrix.config.cpu }}
          laz-branch: fixes_2_2
          fpc-branch: fixes_3_2
    
      - name: Build Simba
        run: |
          export GITHUB_SHORT_SHA=$(git rev-parse --short HEAD)
          
          lazbuild --build-mode=${{ matrix.config.build-mode }} "Source/Simba.lpi"

      - name: Test Simba
        if: matrix.config.test != ''
        run: |
          export DISPLAY=:1
          Xvfb :1 & sleep 2
          
          chmod +x ${{ matrix.config.test }}
          ./${{ matrix.config.test }} --silent --run "Tests/runner"

      - name: Upload Binary 
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ matrix.config.binary }}
          path: ${{ matrix.config.binary }}