name: docs

on:
  workflow_run:
    workflows:
      - build
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true      

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: windows-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_repository.full_name == 'Villavu/Simba' && github.event.workflow_run.head_branch == 'simba2000'
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: ${{ github.event.workflow_run.head_branch }}      
      - name: Download artifact
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "Simba-Win32.exe"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync('Simba-Win32.zip', Buffer.from(download.data));

      - name: Build files
        shell: bash
        run: |
          pip3 install sphinx furo myst-parser
          unzip Simba-Win32.zip
          ./Simba-Win32.exe --run "DocGen/docgen.simba"

      - name: Setup Pages
        uses: actions/configure-pages@v1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: DocGen/build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1